# Generated by Django 2.2.7 on 2021-12-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect4pos',
            old_name='pos1',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='connect4pos',
            old_name='pos2',
            new_name='two',
        ),
        migrations.AlterField(
            model_name='connect4pos',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='game.Game'),
        ),
    ]
