# Generated by Django 2.2.7 on 2021-10-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_visible',
        ),
    ]
