# Generated by Django 2.2.7 on 2021-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211214_0404'),
        ('othello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FourGame',
            new_name='OthelloPos',
        ),
    ]
