# Generated by Django 2.2.7 on 2021-12-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0002_auto_20211214_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othellopos',
            name='pos1',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
        ),
        migrations.AlterField(
            model_name='othellopos',
            name='pos2',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
        ),
    ]
