# Generated by Django 2.2.7 on 2021-12-13 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbstractGame',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='AbstractPlayer',
            new_name='Player',
        ),
    ]
