# Generated by Django 2.2.7 on 2021-12-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211213_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='kind',
        ),
    ]
