# Generated by Django 2.2.7 on 2021-12-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211214_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='game', max_length=20)),
            ],
        ),
    ]
