# Generated by Django 2.2.7 on 2021-12-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamekind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.GameKind'),
        ),
    ]
