# Generated by Django 2.2.7 on 2021-12-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20211217_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='kind',
            field=models.CharField(default='game', max_length=20),
        ),
    ]
