# Generated by Django 2.2.7 on 2021-12-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20211217_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.GameKind'),
        ),
    ]
