# Generated by Django 2.2.7 on 2021-12-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20211217_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='game.GameKind'),
        ),
    ]
