# Generated by Django 2.2.7 on 2021-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamekind',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game/images/'),
        ),
    ]
