# Generated by Django 2.2.7 on 2021-10-28 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20210223_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='image',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.RemoveField(
            model_name='link',
            name='title',
        ),
        migrations.AddField(
            model_name='link',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
